const UPDATE_DATA ='UPDATE_DATA';
const UPDATE_BOSS_DATA ='UPDATE_BOSS_DATA';
const PENSION_TARGET='PENSION_TARGET';
const COORDINATES = 'COORDINATES';
const CUARTO_TARGET='CUARTO_TARGET';
const LOAD_CUARTOS='LOAD_CUARTOS';

export {UPDATE_DATA, UPDATE_BOSS_DATA, PENSION_TARGET, COORDINATES, CUARTO_TARGET, LOAD_CUARTOS}