const UPDATE_DATA ='UPDATE_DATA';
const UPDATE_BOSS_DATA ='UPDATE_BOSS_DATA';
const PENSION_TARGET='PENSION_TARGET';
const COORDINATES = 'COORDINATES';

export {UPDATE_DATA, UPDATE_BOSS_DATA, PENSION_TARGET, COORDINATES}