const UPDATE_DATA ='UPDATE_DATA';
const UPDATE_BOSS_DATA ='UPDATE_BOSS_DATA';
const PENSION_TARGET='PENSION_TARGET';
const COORDINATES = 'COORDINATES';
const CUARTO_TARGET='CUARTO_TARGET';
const LOAD_CUARTOS='LOAD_CUARTOS';
const ENGINE='ENGINE';
const LOAD_COMENTS='LOAD_COMENTS';
const PICTURE1="PICTURE1";
const PICTURE2="PICTURE2";
const PICTURE3="PICTURE3";

export {UPDATE_DATA, UPDATE_BOSS_DATA, PENSION_TARGET, COORDINATES, CUARTO_TARGET, LOAD_CUARTOS, ENGINE,LOAD_COMENTS, PICTURE1, PICTURE2, PICTURE3}